---
- hosts: all
  become: yes
  vars:
    ansible_python_interpreter: "/usr/bin/python3"
  vars_files:
    - vars.yml

  tasks:
    - name: get root user info
      getent:
        database: passwd
        key: root


