---
- hosts: all
  become: yes
  vars:
    ansible_python_interpreter: "/usr/bin/python3"
    GITLAB_HOME: /u01/gitlab
    gitlab_external_url: 
    gitlab_api_version: 

  vars_files:
    - vars.yml

  tasks:
    - include_tasks: 'user_details.yml'
    - include_tasks: 'vault_token.yml'
    - include_tasks: 'vault_token_gitlab.yml'

    - name: GitLab | Store credentials
      ansible.builtin.uri:
        url: "https://{{ vault_host }}/v1/secret/bank"
        method: POST
        headers:
          X-Vault-Token: "{{ vault_token }}"
        body_format: json
        body:
          data:
            db_user: "bank"
            db_pass: "123456"
        validate_certs: false
        status_code: [200, 204]
      no_log: true

    - name: GitLab | Check if path exists
      stat:
        path: /tmp/bank_git/
      register: git_path

    - name: GitLab | Git clone
      shell: |
        git config --global user.name "Helvio Junior"
        git config --global user.email "helvio@labs.sec4us.com.br"
        chown 600 "{{ GITLAB_HOME }}/id_rsa_root"

        cd /tmp
        rm -rf /tmp/bank_api/
        rm -rf /tmp/bank_git/
        git clone https://github.com/sec4us-training/web-api-linux.git bank_api

        GIT_SSH_COMMAND="ssh -i {{ GITLAB_HOME }}/id_rsa_root -p 2222 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" git clone "git@{{gitlab_host}}:sec4us/bank.git" /tmp/bank_git
        rsync -a ./bank_api/bank/* /tmp/bank_git/

        cd /tmp/bank_git/
        find . -path "*/migrations/0*.py" ! -path "*/lib/*" -exec rm -rf {} \;

      ignore_errors: false
      become: yes
      when: not git_path.stat.exists

    - name: Creating a gitignore
      copy:
        dest: "/tmp/bank_git/.gitignore"
        content: |
          # Django #
          *.log
          *.pot
          *.pyc
          __pycache__
          db.sqlite3
          media
          .idea
          *.*~
          *.sqlite3
          .DS_Store
          ._.DS_Store
          **/.DS_Store
          **/._.DS_Store
          
          __MACOSX
          **/__MACOSX

          # Backup files #
          *.bak
          *.zip

          # Migrations file
          **/migrations/*.py

          #reinclude
          !**/migrations/__init__.py

          # If you are using PyCharm #
          .idea/**/workspace.xml
          .idea/**/tasks.xml
          .idea/dictionaries
          .idea/**/dataSources/
          .idea/**/dataSources.ids
          .idea/**/dataSources.xml
          .idea/**/dataSources.local.xml
          .idea/**/sqlDataSources.xml
          .idea/**/dynamic.xml
          .idea/**/uiDesigner.xml
          .idea/**/gradle.xml
          .idea/**/libraries
          *.iws /out/

          # Python #
          *.py[cod]
          *$py.class

          # Distribution / packaging
          .Python build/
          develop-eggs/
          dist/
          downloads/
          eggs/
          .eggs/
          lib/
          lib64/
          parts/
          sdist/
          var/
          wheels/
          *.egg-info/
          .installed.cfg
          *.egg
          *.manifest
          *.spec

          # Installer logs
          pip-log.txt
          pip-delete-this-directory.txt

          # Unit test / coverage reports
          htmlcov/
          .tox/
          .coverage
          .coverage.*
          .cache
          .pytest_cache/
          nosetests.xml
          coverage.xml
          *.cover
          .hypothesis/

          # Jupyter Notebook
          .ipynb_checkpoints

          # pyenv
          .python-version

          # celery
          celerybeat-schedule.*

          # SageMath parsed files
          *.sage.py

          # Environments
          .env
          .venv
          env/
          venv/
          ENV/
          env.bak/
          venv.bak/

          # mkdocs documentation
          /site

          # mypy
          .mypy_cache/

          # Sublime Text #
          *.tmlanguage.cache
          *.tmPreferences.cache
          *.stTheme.cache
          *.sublime-workspace
          *.sublime-project

          # sftp configuration file
          sftp-config.json

          # Package control specific files Package
          Control.last-run
          Control.ca-list
          Control.ca-bundle
          Control.system-ca-bundle
          GitHub.sublime-settings

          # Visual Studio Code #
          .vscode/*
          !.vscode/settings.json
          !.vscode/tasks.json
          !.vscode/launch.json
          !.vscode/extensions.json
          .history

    - name: Creatting Bank config file
      copy:
        dest: "/tmp/bank_git/config.ini"
        force: yes
        content: |
          [GENERAL]
          debug=True

          [DATABASE]
          user = bank
          passwd = 123456
          db = bank
          host = bankdb
          port = 3306
          charset = utf8
          autocommit = False

    - name: Creatting Jenkins file
      copy:
        dest: "/tmp/bank_git/config.ini"
        force: yes
        content: |
          node {
              stage('Checkout') {
                  checkout([
                      $class: 'GitSCM',
                      branches: [[name: '*/main']],
                      userRemoteConfigs: [[
                          url: 'https://{{gitlab_host}}:sec4us/bank.git',
                          credentialsId: 'gitlab-gitscm'
                      ]]
                  ])
              }

              /*
              stage('Gradle + SonarQube') {
                  withSonarQubeEnv('sonarqube') {
                      sh './gradlew clean sonarqube'
                  }
              }

              stage('Quality Gate') {
                  timeout(time: 10, unit: 'MINUTES') {
                      def qg = waitForQualityGate()
                      if (qg.status != 'OK') {
                          error "Quality Gate failed: ${qg.status}"
                      }
                  }
              }
              */

              stage('Build com segredos do Vault') {
                steps {
                  script {
                    def secrets = [
                      [
                        path: 'kv/secret/bank',
                        engineVersion: 2,
                        secretValues: [
                          [envVar: 'DB_USER', vaultKey: 'db_user'],
                          [envVar: 'DB_PASS', vaultKey: 'db_pass']
                        ]
                      ]
                    ]

                    // Usa config global do Vault (url etc.) e autentica via credencial do Jenkins
                    withVault(
                      vaultSecrets: secrets,
                      vaultCredentialId: 'vault',
                      vaultUrl: 'https://{{vault_host}}:8200'
                    ) {
                      sh '''
                        set +x
                        echo "Rodando build..."
                        
                        echo "Conectando ao banco de dados ${DB_USER} com a senha ${DB_PASS}"

                      '''
                    }
                  }
                }
              }
            }
          }


    - name: GitLab | Commit
      shell: |
        cd /tmp/bank_git/
        git branch -m main
        git add .
        git commit -m "Deploy"
        GIT_SSH_COMMAND="ssh -i {{ GITLAB_HOME }}/id_rsa_root -p 2222 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" git push origin main
      ignore_errors: false

