---
- hosts: all
  become: yes
  vars:
    ansible_python_interpreter: "/usr/bin/python3"
    runner_description: "docker-runner-devsecops"
    runner_tags: "docker,linux"
    runner_locked: false
    runner_run_untagged: true
    runner_access_level: "not_protected"   # or "ref_protected" depending on your policy
    runner_home: "/u01/runner"

  vars_files:
    - vars.yml

  tasks:
    - include_tasks: 'user_details.yml'
    - include_tasks: 'vault_token.yml'
    - include_tasks: 'vault_token_gitlab.yml'

    - name: GitLab | Create instance runner configuration (returns glrt token once)
      ansible.builtin.uri:
        url: "{{ gitlab_external_url }}/api/{{ gitlab_api_version }}/user/runners"
        method: POST
        headers:
          PRIVATE-TOKEN: "{{ gitlab_admin_token }}"
        body_format: form-urlencoded
        body:
          runner_type: "instance_type"
          description: "{{ runner_description }}"
          tag_list: "{{ runner_tags }}"
          locked: "{{ runner_locked | ternary('true','false') }}"
          run_untagged: "{{ runner_run_untagged | ternary('true','false') }}"
          access_level: "{{ runner_access_level }}"
        status_code: [201]
        return_content: true
        validate_certs: false
      register: create_runner
      no_log: true

    - name: GitLab | Set runner auth token fact (glrt-...)
      ansible.builtin.set_fact:
        runner_auth_token: "{{ create_runner.json.token }}"
      no_log: true
    
    - name: GitLab | Create directories
      file:
        path: "{{ item.path }}"
        state: directory
        owner: "root"
        group: "root"
        mode: 0777
      with_items:
          - { path: "{{ runner_home }}" }  

    - name: Jenkins | Copy SSH keys
      copy:
        src: "{{ item }}"
        dest: "{{ runner_home }}/ssh_keys"
        owner: "root"
        group: "root"
      with_fileglob:
        - /root/.ssh/id_rsa*

    - name: GitLab | Copy CA root cert
      copy:
        src: "/etc/nginx/certs/root-ca.pem"
        dest: "{{ runner_home }}/root-ca.crt"
        owner: "root"
        group: "root"

    - name: GitLab | Creating runner config file
      copy:
        dest: "{{ runner_home }}/config.toml"
        content: |
          # Global runner settings
          concurrent = 4
          check_interval = 0
          shutdown_timeout = 0

          log_level = "info"
          log_format = "runner"

          [session_server]
            session_timeout = 1800

          # =========================
          # Runner definition
          # =========================
          [[runners]]
            name = "shell-runner-sec4us"
            url = "https://{{gitlab_host}}"

            # Runner authentication token (glrt-...)
            token = "{{runner_auth_token}}"

            executor = "shell"

            # Tags control which jobs can land here
            tags = ["shell", "linux", "ci"]
            run_untagged = true
            locked = false
            access_level = "not_protected"

            output_limit = 40960

            # Environment variables available to jobs
            environment = [
              "TZ=America/Sao_Paulo"
            ]

            # =========================
            # Cache configuration
            # =========================
            [runners.cache]
              Type = "filesystem"
              Path = "/srv/gitlab-runner/cache"
              Shared = true

          # =========================
          # Metrics & monitoring (optional)
          # =========================
          [metrics]
            listen_address = "0.0.0.0:9252"



    - name: GitLab | Creating Dockerfile
      copy:
        dest: "{{ runner_home }}/Dockerfile"
        content: |
          FROM gitlab/gitlab-runner:latest

          USER root

          ENV DEBIAN_FRONTEND=noninteractive
          ENV CA_CERTIFICATES_PATH=/etc/gitlab-runner/certs/
          
          COPY ssh_keys/id_rsa* /root/.ssh/
          COPY root-ca.crt /etc/gitlab-runner/certs/ca.crt
          COPY root-ca.crt /usr/local/share/ca-certificates/root-ca.crt
          RUN update-ca-certificates

          RUN apt update && \
            apt install -y ca-certificates gnupg wget curl rsync jq zip 

          USER root

    - name: GitLab | Build docker image
      shell: |
        cd {{ runner_home }}
        docker build -t registry.labs.sec4us.com.br/ci/linux_runner:lts .
        docker push registry.labs.sec4us.com.br/ci/linux_runner:lts

    - name: GitLab | Creating docker-compose.yml
      copy:
        dest: "{{ runner_home }}/docker-compose.yml"
        content: |
          services:
            gitlab-runner:
              image: registry.labs.sec4us.com.br/ci/linux_runner:lts
              container_name: gitlab-runner
              restart: always

              extra_hosts:
                - "{{vault_host}}:host-gateway"
                - "{{gitlab_host}}:host-gateway"
                - "{{artifactory_host}}:host-gateway"
                - "{{jenkins_host}}:host-gateway"
                - "{{sonar_host}}:host-gateway"
                - "{{web01_host}}:host-gateway"
                - "{{registry_host}}:host-gateway"

              ports:
                - "9252:9252"

              environment:
                - TZ=America/Sao_Paulo

              volumes:
                - /etc/nginx/certs/root-ca.pem:/usr/local/share/ca-certificates/root-ca.crt:ro
                - {{ runner_home }}/config.toml:/etc/gitlab-runner/config.toml:ro

    - name: GitLab | Start service
      shell: |
        cd {{ runner_home }}
        docker compose up -d

    - name: GitLab | Wait for container to be running
      ansible.builtin.command: docker inspect -f '{{ "{{" }}.State.Running{{ "}}" }}' jenkins
      register: jenkins_running
      retries: 60
      delay: 10
      until: jenkins_running.stdout == "true"
      changed_when: false


