---
- hosts: all
  become: yes
  vars:
    ansible_python_interpreter: "/usr/bin/python3"
    GITLAB_HOME: /u01/gitlab
    gitlab_external_url: 
    gitlab_api_version: 

  vars_files:
    - vars.yml

  tasks:
    - include_tasks: 'user_details.yml'
    - include_tasks: 'vault_token.yml'

    - name: Vault | Read gitlab token
      ansible.builtin.uri:
        url: "https://{{ vault_host }}/v1/secret/gitlab/admin"
        method: GET
        headers:
          X-Vault-Token: "{{ vault_token }}"
        validate_certs: false
        status_code: 200
      register: read_secret
      no_log: true

    - name: GitLab | Check if path exists
      stat:
        path: /tmp/bank_api/
      register: git_path

    - name: GitLab | Git clone
      shell: |
        git config --global user.name "Helvio Junior"
        git config --global user.email "helvio@labs.sec4us.com.br"

        cd /tmp
        rm -rf /tmp/bank_api/
        git clone https://github.com/sec4us-training/web-api-linux.git bank_api
        cd bank_api
        rm -rf .git*
      ignore_errors: false
      become: yes
      when: not git_path.stat.exists
      args:
        warn: false

    - name: Creating a gitignore
      copy:
        dest: "/tmp/bank_api/bank/.gitignore"
        content: |
          # Django #
          *.log
          *.pot
          *.pyc
          __pycache__
          db.sqlite3
          media
          .idea
          *.*~
          *.sqlite3
          .DS_Store
          ._.DS_Store
          **/.DS_Store
          **/._.DS_Store
          
          __MACOSX
          **/__MACOSX

          # Config file
          config.ini

          # Backup files #
          *.bak
          *.zip

          # Migrations file
          **/migrations/*.py

          #reinclude
          !**/migrations/__init__.py

          # If you are using PyCharm #
          .idea/**/workspace.xml
          .idea/**/tasks.xml
          .idea/dictionaries
          .idea/**/dataSources/
          .idea/**/dataSources.ids
          .idea/**/dataSources.xml
          .idea/**/dataSources.local.xml
          .idea/**/sqlDataSources.xml
          .idea/**/dynamic.xml
          .idea/**/uiDesigner.xml
          .idea/**/gradle.xml
          .idea/**/libraries
          *.iws /out/

          # Python #
          *.py[cod]
          *$py.class

          # Distribution / packaging
          .Python build/
          develop-eggs/
          dist/
          downloads/
          eggs/
          .eggs/
          lib/
          lib64/
          parts/
          sdist/
          var/
          wheels/
          *.egg-info/
          .installed.cfg
          *.egg
          *.manifest
          *.spec

          # Installer logs
          pip-log.txt
          pip-delete-this-directory.txt

          # Unit test / coverage reports
          htmlcov/
          .tox/
          .coverage
          .coverage.*
          .cache
          .pytest_cache/
          nosetests.xml
          coverage.xml
          *.cover
          .hypothesis/

          # Jupyter Notebook
          .ipynb_checkpoints

          # pyenv
          .python-version

          # celery
          celerybeat-schedule.*

          # SageMath parsed files
          *.sage.py

          # Environments
          .env
          .venv
          env/
          venv/
          ENV/
          env.bak/
          venv.bak/

          # mkdocs documentation
          /site

          # mypy
          .mypy_cache/

          # Sublime Text #
          *.tmlanguage.cache
          *.tmPreferences.cache
          *.stTheme.cache
          *.sublime-workspace
          *.sublime-project

          # sftp configuration file
          sftp-config.json

          # Package control specific files Package
          Control.last-run
          Control.ca-list
          Control.ca-bundle
          Control.system-ca-bundle
          GitHub.sublime-settings

          # Visual Studio Code #
          .vscode/*
          !.vscode/settings.json
          !.vscode/tasks.json
          !.vscode/launch.json
          !.vscode/extensions.json
          .history

    - name: GitLab | Commit
      shell: |
        chown 600 "{{ GITLAB_HOME }}/id_rsa_helvio"
        cd /tmp/bank_api/bank/
        rm -rf .git/*
        find . -path "*/migrations/0*.py" ! -path "*/lib/*" -exec rm -rf {} \;
        git init
        git branch -m main
        git add .
        git commit -m "Deploy"
        git remote add origin "git@{{gitlab_host}}:sec4us/bank.git"
        GIT_SSH_COMMAND="ssh -i {{ GITLAB_HOME }}/id_rsa_helvio -p 2222 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" git push origin main

      ignore_errors: false
      args:
        warn: false

