---
- hosts: all
  become: yes
  vars:
    ansible_python_interpreter: "/usr/bin/python3"
    GITLAB_HOME: /u01/gitlab
    gitlab_external_url: 
    gitlab_api_version: 

  vars_files:
    - vars.yml

  tasks:
    - include_tasks: 'user_details.yml'
    - include_tasks: 'vault_token.yml'
    - include_tasks: 'vault_token_gitlab.yml'

    - name: GitLab | Set project name
      set_fact:
        gitlab_project_group: "sec4us"
        gitlab_project_name: "sonar_helper"
        gitlab_project_visibility: "public"

    - include_tasks: "create_project.yml"

    - name: GitLab | Check if path exists
      stat:
        path: /tmp/sonar_helper/
      register: git_path

    - name: GitLab | Git clone
      shell: |
        git config --global user.name "Helvio Junior"
        git config --global user.email "helvio@labs.sec4us.com.br"
        chown 600 "{{ GITLAB_HOME }}/id_rsa_root"

        rm -rf /tmp/sonar_helper/
        rm -rf /tmp/sonar_helper_git/

        cd /tmp
        git clone https://github.com/sec4us-training/treinamento-devsecops.git sonar_helper

        GIT_SSH_COMMAND="ssh -i {{ GITLAB_HOME }}/id_rsa_root -p 2222 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" git clone "git@{{gitlab_host}}:sec4us/sonar_helper.git" /tmp/sonar_helper_git
        mkdir -p /tmp/sonar_helper_git/ || true
        rsync -a ./sonar_helper/sonar_helper/* /tmp/sonar_helper_git/
      ignore_errors: false
      become: yes
      when: not git_path.stat.exists

    - name: Creating a gitignore
      copy:
        dest: "/tmp/sonar_helper_git/.gitignore"
        content: |
          # Django #
          *.log
          *.pot
          *.pyc
          __pycache__
          db.sqlite3
          media
          .idea
          *.*~
          *.sqlite3
          .DS_Store
          ._.DS_Store
          **/.DS_Store
          **/._.DS_Store
          
          __MACOSX
          **/__MACOSX

          # Backup files #
          *.bak
          *.zip

          # Migrations file
          **/migrations/*.py

          #reinclude
          !**/migrations/__init__.py

          # If you are using PyCharm #
          .idea/**/workspace.xml
          .idea/**/tasks.xml
          .idea/dictionaries
          .idea/**/dataSources/
          .idea/**/dataSources.ids
          .idea/**/dataSources.xml
          .idea/**/dataSources.local.xml
          .idea/**/sqlDataSources.xml
          .idea/**/dynamic.xml
          .idea/**/uiDesigner.xml
          .idea/**/gradle.xml
          .idea/**/libraries
          *.iws /out/

          # Python #
          *.py[cod]
          *$py.class

          # Distribution / packaging
          .Python build/
          develop-eggs/
          dist/
          downloads/
          eggs/
          .eggs/
          lib/
          lib64/
          parts/
          sdist/
          var/
          wheels/
          *.egg-info/
          .installed.cfg
          *.egg
          *.manifest
          *.spec

          # Installer logs
          pip-log.txt
          pip-delete-this-directory.txt

          # Unit test / coverage reports
          htmlcov/
          .tox/
          .coverage
          .coverage.*
          .cache
          .pytest_cache/
          nosetests.xml
          coverage.xml
          *.cover
          .hypothesis/

          # Jupyter Notebook
          .ipynb_checkpoints

          # pyenv
          .python-version

          # celery
          celerybeat-schedule.*

          # SageMath parsed files
          *.sage.py

          # Environments
          .env
          .venv
          env/
          venv/
          ENV/
          env.bak/
          venv.bak/

          # mkdocs documentation
          /site

          # mypy
          .mypy_cache/

          # Sublime Text #
          *.tmlanguage.cache
          *.tmPreferences.cache
          *.stTheme.cache
          *.sublime-workspace
          *.sublime-project

          # sftp configuration file
          sftp-config.json

          # Package control specific files Package
          Control.last-run
          Control.ca-list
          Control.ca-bundle
          Control.system-ca-bundle
          GitHub.sublime-settings

          # Visual Studio Code #
          .vscode/*
          !.vscode/settings.json
          !.vscode/tasks.json
          !.vscode/launch.json
          !.vscode/extensions.json
          .history

    - name: GitLab | Commit
      shell: |
        cd /tmp/bank_git/
        git branch -m main
        git add .
        git commit -m "Deploy"
        GIT_SSH_COMMAND="ssh -i {{ GITLAB_HOME }}/id_rsa_root -p 2222 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" git push origin main
      ignore_errors: false


    - include_tasks: 'vault_token_jenkins.yml'

    #Create Sonar helper CI/CD
    - name: Jenkins | Set fact (Bank CI/CD)
      ansible.builtin.set_fact:
        job_name: "sonar-pipeline"
        job_description: "Sonar Helper pipeline from SCM"
        repo_url: "https://{{gitlab_host}}/sec4us/sonar_helper.git"

    - include_tasks: 'jenkins_pipeline.yml'

    - name: GitLab | List existing projects
      uri:
        url: "{{ gitlab_external_url }}/api/{{ gitlab_api_version }}/projects"
        method: "GET"
        headers:
          PRIVATE-TOKEN: "{{ gitlab_admin_token }}"
        validate_certs: false
        return_content: true
        status_code: [200, 502, 503, 504]
      register: projects_list_output
      until: projects_list_output.status == 200
      retries: 30
      delay: 10

    - name: "Check if project is already exists"
      set_fact:
        project_exists: "{{ gitlab_project_group + '/' + gitlab_project_name in\
          (projects_list_output.json | map(attribute='path_with_namespace')  | list) }}"

    - name: GitLab | Get project ID
      set_fact:
        gitlab_project_id: "{{ item.id }}"
      loop: "{{ projects_list_output.json }}"
      when:
        - project_exists
        - item.path_with_namespace == gitlab_project_group + '/' + gitlab_project_name

