---
- hosts: all
  become: yes
  vars:
    ansible_python_interpreter: "/usr/bin/python3"
    WEB_HOME: /u01/www

  vars_files:
    - vars.yml

  tasks:
    - include_tasks: 'user_details.yml'

    - name: GitLab | Configuring NGINX
      copy:
        dest: "/etc/nginx/conf.d/www.conf"
        owner: root
        group: root
        mode: 0644
        force: yes
        content: |
          server {
              listen        443 ssl;
              server_name {{ web01_host }};

              ssl_certificate      /etc/nginx/certs/ssl.cer;
              ssl_certificate_key  /etc/nginx/certs/ssl.key;

              root /dev/null;
              index index.html index.htm;
              try_files $uri $uri/ $uri/404 =404;

              location / {
                  proxy_http_version    1.1;
                  proxy_ssl_verify      off;
                  proxy_set_header      Host                $host;
                  proxy_set_header      X-Real-IP           $remote_addr;
                  proxy_set_header      X-Forwarded-For     $remote_addr;
                  proxy_set_header      X-Forwarded-Proto   $scheme;
                  proxy_pass http://127.0.0.1:8054;
              }

          }

    - name: Web01 | Reload nginx config
      shell: |
        nginx -s reload

    - name: Web01 | Create directories
      file:
        path: "{{ item.path }}"
        state: directory
        owner: "root"
        group: "root"
        mode: 0775
      with_items:
          - { path: "{{ WEB_HOME }}" }
          - { path: "{{ WEB_HOME }}/data" }
          - { path: "{{ WEB_HOME }}/data/.git" }
    
    - name: Web01 | Create README.txt
      copy:
        dest: "{{ WEB_HOME }}/data/README.txt"
        owner: root
        group: root
        mode: 0644
        force: yes
        content: |
          Web01 – Static Content Service
          =============================

          Este diretório contém os arquivos estáticos atualmente servidos pelo Web01.
          O serviço foi configurado de forma simples para facilitar testes, análises
          e validações rápidas em ambiente controlado.

          Estrutura visível:
          - index.html
          - assets/
          - README.txt

          ATENÇÃO:
          Este NÃO é o projeto completo.

          Durante o desenvolvimento inicial, o repositório Git foi mantido no mesmo
          diretório raiz utilizado pelo servidor web. Por questões de compatibilidade
          e rapidez no deploy, o diretório .git nunca foi separado do conteúdo servido.

          Isso significa que:
          - Apenas parte do projeto está visível na raiz
          - O histórico completo ainda existe no diretório .git
          - Arquivos removidos ou alterados podem ser encontrados no histórico

          Dica para análise:
          Caso você esteja procurando por arquivos que “sumiram”, versões antigas,
          configurações anteriores ou informações sensíveis, o diretório .git pode
          conter exatamente o que você precisa.

          Em revisões anteriores, a análise direta do .git revelou:
          - commits antigos
          - arquivos que não deveriam mais existir
          - decisões que não aparecem no estado atual do projeto

          Nota final:
          Nem tudo que importa está listado pelo index do diretório principal.
          Às vezes, a resposta está no histórico.

          Boa sorte.
          Equipe Sec4US treinamentos - DevSecOps

    - name: Web01 | Creating httpd-web01.conf
      copy:
        dest: "{{ WEB_HOME }}/httpd-web01.conf"
        content: |
          ServerName {{ web01_host }}

          Listen 80

          # =========================
          # MPM (OBRIGATÓRIO)
          # =========================
          LoadModule mpm_event_module modules/mod_mpm_event.so

          # =========================
          # Módulos básicos
          # =========================
          LoadModule unixd_module modules/mod_unixd.so
          LoadModule authz_core_module modules/mod_authz_core.so
          LoadModule authz_host_module modules/mod_authz_host.so
          LoadModule dir_module modules/mod_dir.so
          LoadModule autoindex_module modules/mod_autoindex.so
          LoadModule mime_module modules/mod_mime.so
          LoadModule log_config_module modules/mod_log_config.so
          LoadModule headers_module modules/mod_headers.so

          TypesConfig conf/mime.types

          # =========================
          # Document Root
          # =========================
          DocumentRoot "/usr/local/apache2/htdocs"

          <Directory "/usr/local/apache2/htdocs">
              Options Indexes FollowSymLinks
              AllowOverride None
              Require all granted
          </Directory>

          # =========================
          # Directory listing
          # =========================
          IndexOptions FancyIndexing HTMLTable NameWidth=* Charset=UTF-8
          DirectoryIndex index.html index.htm

          AddDefaultCharset UTF-8

          # =========================
          # Logs (stdout / stderr)
          # =========================
          ErrorLog /proc/self/fd/2
          CustomLog /proc/self/fd/1 combined

    - name: Web01 | Get .git path
      ansible.builtin.set_fact:
        git_dir_path: "{{ playbook_dir }}/.git"

    - name: Web01 | Sync files
      shell: |
        rsync -a {{ git_dir_path }}/* {{ WEB_HOME }}/data/.git

    - name: Web01 | Deploy to gitlab
      shell: |
        cd {{ WEB_HOME }}/data/
        git remote remove origin || true
        git remote add origin git@{{gitlab_host}}:sec4us/devsecops.git
        GIT_SSH_COMMAND="ssh -i {{ GITLAB_HOME }}/id_rsa_root -p 2222 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" git push origin main
      ignore_errors: false

    - name: Web01 | Creating docker-compose.yml
      copy:
        dest: "{{ WEB_HOME }}/docker-compose.yml"
        content: |
          services:
            apache:
              image: httpd:2.4
              container_name: apache-web01
              restart: always

              ports:
                - "8054:80"

              volumes:
                # Conteúdo servido
                - {{ WEB_HOME }}/data:/usr/local/apache2/htdocs

                # Configuração customizada
                - {{ WEB_HOME }}/httpd-web01.conf:/usr/local/apache2/conf/httpd.conf:ro

    - name: Web01 | Start service
      shell: |
        cd {{ WEB_HOME }}
        docker compose up -d

    - name: Web01 | Wait for container to be running
      ansible.builtin.command: docker inspect -f '{{ "{{" }}.State.Running{{ "}}" }}' apache-web01
      register: web01_running
      retries: 60
      delay: 10
      until: web01_running.stdout == "true"
      changed_when: false

    - name: Web01 | Wait for port 8054
      ansible.builtin.wait_for:
        host: 127.0.0.1
        port: 8054
        delay: 10
        timeout: 300

