---
- hosts: all
  become: yes
  vars:
    ansible_python_interpreter: "/usr/bin/python3"
    GITLAB_HOME: /u01/gitlab
    gitlab_external_url: 
    gitlab_api_version: 

  vars_files:
    - vars.yml

  tasks:
    - include_tasks: 'user_details.yml'
    - include_tasks: 'vault_token.yml'

    - name: GitLab | Configuring NGINX
      copy:
        dest: "/etc/nginx/conf.d/gitlab.conf"
        owner: root
        group: root
        mode: 0644
        force: yes
        content: |
          server {
              listen        443 ssl;
              server_name {{ gitlab_host }};

              ssl_certificate      /etc/nginx/certs/ssl.cer;
              ssl_certificate_key  /etc/nginx/certs/ssl.key;

              root /dev/null;
              index index.html index.htm;
              try_files $uri $uri/ $uri/404 =404;

              location / {
                  proxy_ssl_verify      off;
                  proxy_set_header      Host                $host;
                  proxy_set_header      X-Real-IP           $remote_addr;
                  proxy_set_header      X-Forwarded-For     $remote_addr;
                  proxy_set_header      X-Forwarded-Proto   $scheme;
                  proxy_pass http://127.0.0.1:8180;
              }
          
              # Protege o GITLab caso não defina a senha do Admin na instalacao
              location /users/password/edit {
                  return 403;
              }

          }

    - name: GitLab | Reload nginx config
      shell: |
        nginx -s reload

    - name: GitLab | Create directories
      file:
        path: "{{ item.path }}"
        state: directory
        owner: "root"
        group: "root"
        mode: 0775
      with_items:
          - { path: "{{ GITLAB_HOME }}/config" }
          - { path: "{{ GITLAB_HOME }}/logs" }
          - { path: "{{ GITLAB_HOME }}/data" }
    
    - name: GitLab | Generate admin's SSH key
      user:
        name: "admin"
        generate_ssh_key: yes
        ssh_key_type: rsa
        ssh_key_bits: 4096
        ssh_key_file: "{{ GITLAB_HOME }}/id_rsa_root"
        force: no

    - name: GitLab | Creating docker-compose.yml
      copy:
        dest: "{{ GITLAB_HOME }}/docker-compose.yml"
        content: |
          services:
            gitlab:
              image: 'gitlab/gitlab-ce:latest'
              container_name: gitlab
              restart: always
              hostname: '{{ gitlab_host }}'
              environment:
                TZ: America/Sao_Paulo
                GITLAB_OMNIBUS_CONFIG: |
                  external_url 'https://{{ gitlab_host }}'
                  gitlab_rails['gitlab_shell_ssh_port'] = 22
                  nginx['enable'] = false
                  gitlab_workhorse['listen_network'] = "tcp"
                  gitlab_workhorse['listen_addr'] = "0.0.0.0:8180"

              ports:
                - '8180:8180'
                - '2222:22'

              volumes:
                - '{{ GITLAB_HOME }}/config:/etc/gitlab'
                - '{{ GITLAB_HOME }}/logs:/var/log/gitlab'
                - '{{ GITLAB_HOME }}/data:/var/opt/gitlab'

              shm_size: '256m'

    - name: GitLab | Start gitlab
      shell: |
        cd {{ GITLAB_HOME }}
        docker compose up -d

    - name: GitLab | Wait for gitlab container to be running
      ansible.builtin.command: docker inspect -f '{{ "{{" }}.State.Running{{ "}}" }}' gitlab
      register: gitlab_running
      retries: 30
      delay: 5
      until: gitlab_running.stdout.strip() == "true"
      changed_when: false
    
    - name: GitLab | Wait for internal services
      ansible.builtin.command: docker exec gitlab gitlab-ctl status
      register: gitlab_status
      retries: 40
      delay: 15
      until: >
        gitlab_status.stdout is search("run: postgresql") and
        gitlab_status.stdout is search("run: sshd") and
        gitlab_status.stdout is search("run: gitaly")
      changed_when: false

    - name: GitLab | Wait for API to be ready
      ansible.builtin.command: docker exec gitlab bash -lc "curl -s http://127.0.0.1:8180/-/health || true"
      register: gitlab_status
      retries: 40
      delay: 15
      until: >
        gitlab_status.stdout is search("GitLab OK")
      changed_when: false

    - name: GitLab | Reconfigure
      ansible.builtin.command: docker exec gitlab gitlab-ctl reconfigure
      register: reconfigure_out
      retries: 10
      delay: 15
      until: reconfigure_out.rc == 0
      changed_when: true

    - name: GitLab | Generating admin password
      ansible.builtin.command: >
        python3 -c 'import base64; obf=bytes([61,61,81,75,113,111,87,79,47,52,72,76,112,53,104,71,74,56,103,98,53,56,84,67]); key=0x5A; print(bytes([b^key for b in base64.b64decode(obf[::-1])]).decode())'
      register: gitlab_root_adm_out
      retries: 10
      delay: 15
      until: gitlab_root_adm_out.rc == 0
      changed_when: true
      no_log: true

    - name: GitLab | Parse do output
      ansible.builtin.set_fact:
        gitlab_root_password: "{{ gitlab_root_adm_out.stdout | trim }}"
      changed_when: false
      no_log: true

    - name: GitLab | Change admin password via rails runner
      become: true
      ansible.builtin.command: >
        docker exec gitlab gitlab-rails runner
        "u = User.where(username: 'root').first;
         u.password_automatically_set=false; 
         u.password = '{{ gitlab_root_password }}'; 
         u.password_confirmation = '{{ gitlab_root_password }}'; 
         u.save!"
      changed_when: true

    - name: GitLab | Generating admin access token
      set_fact:
        gitlab_root_token: "{{ lookup('community.general.random_string', upper=True, numbers=True, special=false, length=30) }}"

    - name: GitLab | Create admin token via rails runner
      ansible.builtin.command: >
        docker exec gitlab gitlab-rails runner
        "u = User.where(username: 'root').first;
         t = PersonalAccessToken.new(user: u, name: 'root token', scopes: ['api','sudo'], expires_at: 1.year.from_now); 
         t.set_token('{{gitlab_root_token}}'); 
         t.save!
         puts t.token"
      changed_when: true
      no_log: true

    - name: Disable Auto DevOps globally (instance level)
      ansible.builtin.uri:
        url: "https://{{ gitlab_host }}/api/v4/application/settings"
        method: PUT
        headers:
          PRIVATE-TOKEN: "{{ gitlab_root_token }}"
          Content-Type: "application/json"
        body_format: json
        body:
          auto_devops_enabled: false
        status_code: [200]
        validate_certs: false
      register: gitlab_settings
      no_log: true

    - name: GitLab | Store credentials
      ansible.builtin.uri:
        url: "https://{{ vault_host }}/v1/secret/gitlab/admin"
        method: POST
        headers:
          X-Vault-Token: "{{ vault_token }}"
        body_format: json
        body:
          url: "https://{{ gitlab_host }}"
          username: "root"
          password: "{{ gitlab_root_password }}"
          personal_token: "{{ gitlab_root_token }}"
        validate_certs: false
        status_code: [200, 204]
      no_log: true

    - name: Get SSH public key
      slurp:
        src: "{{ GITLAB_HOME }}/id_rsa_root.pub"
      register: remote_ssk_pub_encoded
    
    - include_tasks: 'vault_token_gitlab.yml'

    - name: "Set data"
      set_fact:
        gitlab_username: "root"
        gitlab_ssh_key: "{{remote_ssk_pub_encoded.content | b64decode}}"

    - include_tasks: "create_user_sshkey.yml"

