---
- name: Jenkins | Get crumb (CSRF token)
  ansible.builtin.uri:
    url: "https://{{ jenkins_host }}/crumbIssuer/api/json"
    method: GET
    user: "admin"
    password: "{{ jenkins_admin_password }}"
    force_basic_auth: yes
    validate_certs: false
    return_content: yes
    status_code: 200
  register: crumb_json

- name: Jenkins | Build CSRF header
  set_fact:
    jenkins_crumb_header: >-
      {{
        {
          crumb_json.json.crumbRequestField:
          crumb_json.json.crumb
        }
      }}

- name: Jenkins | Create gitlab in global domain
  ansible.builtin.uri:
    url: "https://{{ jenkins_host }}/credentials/store/system/domain/_/createCredentials"
    #url: "https://webhook.site/686def12-6e88-4a07-9e0c-c146a54126b9"
    method: POST
    user: "admin"
    password: "{{ jenkins_admin_password }}"
    force_basic_auth: true
    return_content: true
    headers: "{{ jenkins_crumb_header | combine({'Cookie': crumb_json.cookies_string}) | combine({'Content-Type': 'application/x-www-form-urlencoded'}) }}"
    body_format: form-urlencoded
    body: 
      json: "{{ json_body | to_json }}"
    status_code: [200, 201, 204, 409, 302]
    validate_certs: false
  register: create_cred
  no_log: true

- name: Jenkins | Check if credential exists
  ansible.builtin.uri:
    url: "https://{{ jenkins_host }}/credentials/store/system/domain/_/credential/{{ json_body.credentials.id }}/api/json"
    method: GET
    user: "admin"
    password: "{{ jenkins_admin_password }}"
    force_basic_auth: true
    return_content: true
    headers: "{{ jenkins_crumb_header | combine({'Cookie': crumb_json.cookies_string}) }}"
    follow_redirects: none
    status_code: [200, 404, 302]
    validate_certs: false
  register: cred_check
  no_log: true

- name: Fail if not found (or redirected to login)
  ansible.builtin.fail:
    msg: >-
      Credential {{ cred_id }} not found (404) or Jenkins redirected (302) - likely auth/session/crumb issue.
  when: cred_check.status != 200