---
- hosts: all
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3
    REGISTRY_HOME: "/u01/registry"

  vars_files:
    - vars.yml

  tasks:
        
    - name: Docker | Ensure prerequisites are installed
      ansible.builtin.apt:
        name:
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present
        update_cache: yes

    - name: Docker | Ensure keyrings directory exists
      ansible.builtin.file:
        path: /usr/share/keyrings
        state: directory
        mode: "0755"

    - name: Docker | Download Docker GPG key (ASCII)
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /tmp/docker.gpg
        mode: "0644"

    - name: Docker | Dearmor Docker GPG key into keyring
      ansible.builtin.command: >
        gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg /tmp/docker.gpg
      args:
        creates: /usr/share/keyrings/docker-archive-keyring.gpg

    - name: Docker | Get Ubuntu codename
      ansible.builtin.command: lsb_release --codename --short
      register: ubuntu_codename
      changed_when: false

    - name: Docker | Add Docker apt repository (signed-by keyring)
      ansible.builtin.apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu {{ ubuntu_codename.stdout }} stable"
        filename: docker
        state: present

    - name: Docker | Update apt cache and upgrade packages
      ansible.builtin.apt:
        update_cache: yes
        upgrade: dist

    - name: Docker | Install Docker CE
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present

    - name: Docker | Enable and start Docker
      ansible.builtin.service:
        name: docker
        state: started
        enabled: true

    - name: Docker | Add user to docker group
      ansible.builtin.user:
        name: "{{ local_username }}"
        groups: docker
        append: true


    - name: Docker | Configuring NGINX
      copy:
        dest: "/etc/nginx/conf.d/registry.conf"
        owner: root
        group: root
        mode: 0644
        force: yes
        content: |
          server {
              listen        443 ssl;
              server_name {{ registry_host }};

              ssl_certificate      /etc/nginx/certs/ssl.cer;
              ssl_certificate_key  /etc/nginx/certs/ssl.key;

              root /dev/null;
              index index.html index.htm;
              try_files $uri $uri/ $uri/404 =404;

              client_max_body_size 100000M;

              location / {
                  proxy_http_version    1.1;
                  proxy_ssl_verify      off;
                  proxy_set_header      Host                $host;
                  proxy_set_header      X-Real-IP           $remote_addr;
                  proxy_set_header      X-Forwarded-For     $remote_addr;
                  proxy_set_header      X-Forwarded-Proto   $scheme;
                  proxy_pass http://127.0.0.1:5000;
              }
          
          }

    - name: Jenkins | Reload nginx config
      shell: |
        nginx -s reload

    - name: Docker | Create directories
      file:
        path: "{{ item.path }}"
        state: directory
        owner: "root"
        group: "root"
        mode: 0777
      with_items:
          - { path: "{{ REGISTRY_HOME }}" }    

    - name: Docker | Creating docker-compose.yml
      copy:
        dest: "{{ REGISTRY_HOME }}/docker-compose.yml"
        content: |
          services:
            docreg:
              image: registry:2
              ports:
                - "5000:5000"
              volumes:
                - registry-data:/var/lib/registry
              environment:
                REGISTRY_STORAGE_DELETE_ENABLED: "true"

          volumes:
            registry-data:

    - name: Docker | Start service
      shell: |
        cd {{ REGISTRY_HOME }}
        docker compose up -d

    - name: Docker | Wait for port 5000
      ansible.builtin.wait_for:
        host: 127.0.0.1
        port: 5000
        delay: 10
        timeout: 300

