- name: General | Check ansible_vault.key
  ansible.builtin.stat:
    path: "{{ vault_home }}/ansible_vault.key"
  register: vault_key_stat
  changed_when: false

- name: General | File not found 
  ansible.builtin.fail:
    msg: "Vault token file does not exists."
  when: vault_key_stat.stat.exists == false

- name: General | Get vault token
  ansible.builtin.slurp:
    src: "{{ vault_home }}/ansible_vault.key"
  register: vault_key_raw
  no_log: true

- name: Definir variável vault_token
  ansible.builtin.set_fact:
    vault_token: "{{ vault_key_raw.content | b64decode | trim }}"
  no_log: true