package com.sec4us.lab.sonarhelper.config;

/**
 * Lab-only configuration for the SonarQube admin endpoint.
 *
 * Generated by templating-maven-plugin: SONAR_ADMIN_USER and
 * SONAR_ADMIN_PASSWORD are injected from environment variables at build time
 * (see <properties> in pom.xml).
 */
public final class SonarConfig {

    public static final String SONAR_URL = "https://sonar.labs.sec4us.com.br";
    public static final String SONAR_ADMIN_USER = "${sonar.admin.user}";
    public static final String SONAR_ADMIN_PASSWORD = "${sonar.admin.password}";

    private SonarConfig() {
    }
}
